[programs.localnet]
tutorial = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/oli/.config/solana/id.json"

[scripts]
test = "node tests/tutorial.js"
